### PR TITLE
Fix focus-visible for Safari

### LINKED ISSUE #723: :focus-visible selector not supported in Safari but used across almost all of our focusable elements
## Description

[`:focus-visible` is unsupported in any current version of Safari](https://caniuse.com/?search=focus-visible)

## Reproduction

1. Open non tech-preview Safari (the current version or an iPad or iPhone safari)
2. Focus the header buttons using the keyboard
3. Note the lack of focus styles on any button

## Expectation

Buttons should have focus styles in all browsers

## Environment

 - Browser: Safari

## Additional context

Found while testing https://github.com/WordPress/openverse-frontend/pull/695

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #723  by @sarayourfriend 

## Description

Fixes focus-visible for Safari using a polyfill and a postcss plugin.

## Testing Instructions

Checkout this branch and run it in Safari and verify that focus rings appear on elements that need them when focused via the keyboard (like buttons in the header).

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/layouts/blank.vue [hunk 1]
```diff
@@ -1,3 +1,9 @@
 <template>
   <Nuxt />
 </template>
+
+<script>
+import '~/utils/safe-focus-visible-polyfill'
```
Comment (sarayourfriend) [inline src/layouts/blank.vue:6]: Is there a better way to import this into all layouts client-side only? I tried using a setting in `head` object in nuxt-config but I wasn't sure how to get the polyfill file referenced properly 🤔 Would we need to copy it out of `node_modules` during the build step or something into the static folder so it would get copied into the build output and we could reference it in a script element in the head?

File: src/utils/safe-focus-visible-polyfill.js [hunk 2]
```diff
@@ -0,0 +1 @@
+if (process.client) require('focus-visible')
```
Comment (sarayourfriend) [inline src/utils/safe-focus-visible-polyfill.js:1]: `focus-visible` breaks SSR so we need to guard it to only be imported on the client.

**Review by dhruvkb — COMMENTED** [review]
I'm not well versed with Nuxt config but could we add this somewhere globally instead of importing in every layout?

**Comment by sarayourfriend** [comment]
@dhruvkb Is there a global root file for Nuxt? I couldn't really find one that is accessible to edit, that's why I placed it in the layouts 🤔

**Comment by dhruvkb** [comment]
There has to be some level above the layouts. I'll dig through the docs.

**Comment by dhruvkb** [comment]
If we can do that, it'll be great. But considering the a11y implications of completely forgetting about a browser, we could also merge this as a quickfix for now.

**Comment by sarayourfriend** [comment]
Well, either way we'll have to deploy the fix which probably won't happen for another couple hours anyway.

@zackkrida can you see any reason not to use a CDN version of the polyfill (provided we include all the appropriate integrity checks?)

We could use https://unpkg.com/focus-visible@5.2.0/dist/focus-visible.js?meta as we already rely on Cloudflare anyway.

**Comment by zackkrida** [comment]
I'm comfortable with unpkg + integrity checks, I don't see any issue there!

**Comment by sarayourfriend** [comment]
Went the plugin route that @obulat recommended. It's much more sensible!

**Review by zackkrida — APPROVED** [review]
This is working well on desktop Safari. A good way for others to test this is comparing the hover state of the homepage content type chooser on localhost vs. https://wordpress.org/openverse/

**Review by dhruvkb — APPROVED** [review]
