### PR TITLE
fix focus outline placement button

### LINKED ISSUE #1110: Fix play/pause button focus outline placement
## Description

Noted here: https://github.com/WordPress/openverse-frontend/pull/1069#issuecomment-1064702601

## Reproduction

1.  Focus the play pause button using the keyboard and observe that the focus outline is outside the button boundaries and is cut off by the waveform on the joining edge.

## Additional context

The following patch will resolve the issue:

```diff
diff --git a/src/components/VAudioTrack/VPlayPause.vue b/src/components/VAudioTrack/VPlayPause.vue
index b6326e46..926f957c 100644
--- a/src/components/VAudioTrack/VPlayPause.vue
+++ b/src/components/VAudioTrack/VPlayPause.vue
@@ -2,9 +2,10 @@
   <VIconButton
     v-bind="$attrs"
     :tabindex="layout === 'box' ? -1 : 0"
-    class="play-pause flex-shrink-0 bg-dark-charcoal border-dark-charcoal text-white disabled:opacity-70"
+    class="play-pause flex-shrink-0 bg-dark-charcoal border-dark-charcoal text-white disabled:opacity-70 focus-visible:border-pink focus-visible:outline-none focus-visible:shadow-ring"
     :icon-props="{ iconPath: icon }"
     :aria-label="$t(label)"
+    variant="plain-dangerous"
     @click="handleClick"
   />
 </template>
diff --git a/src/components/VIconButton/VIconButton.vue b/src/components/VIconButton/VIconButton.vue
index cf83fd18..b953630f 100644
--- a/src/components/VIconButton/VIconButton.vue
+++ b/src/components/VIconButton/VIconButton.vue
@@ -1,6 +1,6 @@
 <template>
   <VButton
-    variant="plain"
+    :variant="variant"
     size="disabled"
     class="icon-button flex flex-shrink-0 items-center justify-center border-1.5 active:shadow-ring"
     :class="[...buttonSizeClasses]"
@@ -49,6 +49,14 @@ export default {
      * documentation on `VIcon`.
      */
     iconProps: {},
+    /**
+     * `variant` prop to pass to `VButton`. See `VButton` for documentation
+     * and possible values.
+     */
+    variant: {
+      type: String,
+      default: 'plain',
+    },
   },
   setup(props, { attrs }) {
     const type = attrs['type'] ?? 'button'
```

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by kb-0311**
## Fixes

Fixes #1110 by @sarayourfriend 

## Description

FIxes the play pause button outline placement as suggested by @sarayourfriend 
SIDE NOTE -> I had already submitted this PR but I had to delete my forked repo because I had by mistake messed up the main branch in that repo, sorry, won't happen again. This caused my previous PR to auto-close.
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kb-0311** [comment]
as discussed earlier, I will resubmit the dev dependency update PR (now closed) once #1131 is merged and ready to go : )

**Comment by zackkrida** [comment]
@dhruvkb @sarayourfriend could you both review this when you have a chance?

File: src/components/VAudioTrack/VPlayPause.vue [hunk 1]
```diff
@@ -2,9 +2,10 @@
   <VIconButton
     v-bind="$attrs"
     :tabindex="layout === 'box' ? -1 : 0"
-    class="play-pause flex-shrink-0 bg-dark-charcoal border-dark-charcoal text-white disabled:opacity-70"
+    class="play-pause flex-shrink-0 bg-dark-charcoal border-dark-charcoal text-white disabled:opacity-70 focus-visible:border-pink focus-visible:outline-none focus-visible:shadow-ring"
     :icon-props="{ iconPath: icon }"
     :aria-label="$t(label)"
+    variant="plain-dangerous"
```
Comment (dhruvkb) [inline src/components/VAudioTrack/VPlayPause.vue:8]: This isn't directly related to this PR but `plain-dangerous` is a confusing variant name, given that it can be used for a button that's not dangerous. It can be improved.

**Review by dhruvkb — CHANGES_REQUESTED** [review]

File: src/components/VAudioTrack/VPlayPause.vue (hunk 1 above)
Comment (sarayourfriend) [reply src/components/VAudioTrack/VPlayPause.vue:8]: Do you have a suggestion Dhruv? I suggested the `dangerous` name modeled more or less after similarly dangerous tools like React's `dangerouslySetInnerHTML`. I can see that it could be confused with a "dangerous" button (i.e., a button leading to a destructive action) but I can't think of any other terms that coveys the sense of "you probably shouldn't use this". `variant="none"` is an alternative one we could use but it doesn't convey the sense that the user needs to take on extra responsibility when using it to correctly implement accessible patterns.

File: src/components/VIconButton/VIconButton.vue [hunk 2]
```diff
@@ -49,6 +49,14 @@ export default {
...
      */
     iconProps: {},
+    /**
+     * `variant` prop to pass to `VButton`. See `VButton` for documentation
+     * and possible values.
+     */
+    variant: {
+      type: String,
+      default: 'plain',
+    },
```
[the remark this answers is not in the document]
Comment (sarayourfriend) [reply src/components/VIconButton/VIconButton.vue:59]: I actually tried that originally when I made the suggestions for this PR but it did not work for some reason. Maybe you can try checking out the branch and getting it to work? The issue I was seeing is that default variant would get used instead of the one being passed through `v-bind` :disappointed:

**Review by sarayourfriend — COMMENTED** [review]
I'm find with this, but I also proposed the code that is being used here, verbatim. I'm not sure I should be the one reviewing this necessarily.

Can someone else @WordPress/openverse-frontend take a look at this?

File: src/components/VAudioTrack/VPlayPause.vue (hunk 1 above)
Comment (dhruvkb) [reply src/components/VAudioTrack/VPlayPause.vue:8]: How about "plain--avoid"? The `--avoid` suffix can add that little bit of friction to discourage it's usage while not confusing with the "danger" convention we use for destructive actions.

Comment (sarayourfriend) [reply src/components/VAudioTrack/VPlayPause.vue:8]: Works for me!

Comment (dhruvkb) [reply src/components/VAudioTrack/VPlayPause.vue:8]: Created #1181.

**Comment by kb-0311** [comment]
I am a little confused about what I am supposed to do here ... :smiling_face_with_tear:

File: src/components/VAudioTrack/VPlayPause.vue (hunk 1 above)
Comment (dhruvkb) [inline src/components/VAudioTrack/VPlayPause.vue:8]:
```suggestion
    :button-props="{ variant: 'plain-dangerous' }"
```

**Review by dhruvkb — CHANGES_REQUESTED** [review]
@kb-0311 this is what I meant.

Notice how `VIconButton` binds `iconProps` directly to the `VIcon` component using `v-ind=""`? We can do the same with the `VButton` as well, by accepting a `buttonProps` prop and binding it to the component.

Then all the props we want to pass to the inner `VButton` can be passed as an object to `VIconButton`.

@sarayourfriend I verified that these changes do work.

image

**Comment by kb-0311** [comment]
@dhruvkb thanks for clearing that up, I committed your requested changes as is. 👍

**Review by dhruvkb — APPROVED** [review]
Looks good to me now, need another reviewer to approve it and we should be good to go!
