### PR TITLE
All results audio tabbing, single result link, and play/pause fixes

### LINKED ISSUE #662: All results boxed audio a11y
## Description

From @sarayourfriend 

Audio results need to be composite items with the play/pause button removed from the default tab order. Currently tabbing through each result is fine until you hit an audio result which will tab from the result link into the play/pause button before moving on to the next result. The tab order should just be each result. This happens both with and without VoiceOver activated.

With VoiceOver, the audio results are not announcing their title. I think this would be fixed with the composite items as I believe they require `aria-label` which would announce the title.

Audio links are also missing an `aria-label` so all audio links just read "link, Audio player" in VoiceOver.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #662 by @zackkrida 

## Description

- Spacebar or play button click to play/pause on boxed audio
- Click or enter to visit single result

We probably still need to announce to screen reader users that space will play/pause and click will visit the single result. There may be a way to do what I'm doing _and_ wrap in a NuxtLink for improved usability.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VIconButton/VIconButton.vue [hunk 1]
```diff
@@ -5,7 +5,11 @@
     :type="type"
     v-on="$listeners"
   >
-    <VIcon :class="[...iconSizeClasses]" v-bind="iconProps" />
+    <VIcon
+      class="pointer-events-none"
```
Comment (zackkrida) [inline src/components/VIconButton/VIconButton.vue:9]: This allows icon click events to pass through to their parent element, which makes sure the `target` of icon buttons clicks is always the button, not the internal icon.

**Comment by zackkrida** [comment]
Merging, even if this has problems it's still vastly preferable to the previous approach.
