### PR TITLE
Convert nav store to an options store

### LINKED ISSUE #1254: Correctly hydrating the server state in Pinia setup stores
## Problem

We are almost done converting Vuex stores to Pinia ([milestone](https://github.com/WordPress/openverse-frontend/milestone/5)). However, we are incorrectly re-initializing the store on the client side instead of reusing the server-side state, and this is causing a lot of errors. 

## Description

All of the stores are now converted to Pinia setup stores.

Final conversion surfaced a very important flaw in this conversion process. During the state hydration on the client, the Pinia store setup function is ran again as is. This means that instead of reusing the state passed from the server, we are re-creating the state with initial values. This causes numerous errors in the app logic.
For example, when you click on 'Load more' button on a server-rendered search page, the media fetch state page value is set to undefined, so we are re-fetching the same page that has already been fetched. Other bugs such as the audio search page with fewer than 20 results being unresponsive, and no change when you select an extension filter and decelect it, are also caused by the incorrect state on the client.

The solution I propose (and try out in the Provider store PR) is to add a custom function for initializing the state by setting it to the initial value on the server, and adding our own hydration solution on the client. Nuxt context is not injected inside the setup store setup function. However, it is available as part of the `$nuxt` property of the global `window` object.
```
const initialState = { searchType: ALL_MEDIA }

const initializeState = () => {
    // add `isClient` checks to make sure window is not undefined 
    const serverState = window.$nuxt.context.pinia.state.search
    if (serverState) {
        // Making sure that the state is a simple object, not a proxy or a ref.
        return JSON.parse(JSON.stringify(serverState))
    } else {
        return initialState
    }
}

const searchStore = defineStore('search', () => {
    const state = reactive(initializeState())

    return { state }
})
```

This can only work if we can serialize and deserialize the state correctly. Here, the problem in the `media` store is with the current implementation of the `fetchState`, which is a composable that returns both simple properties, but also functions to change the `fetchState`. The functions cannot be stringified, and need to be filtered out when hydrating the state. We also cannot use a computed that would only return the inner simple `FetchState` object from this computed because Pinia treats computed refs as getters, and it only passes the state (i.e. the `ref`s and `reactive`s) from the server to client as part of the `window.$nuxt.context` value.
Instead, we can create the `_fetchState` as an inner composable that would handle state updates, and a fetchState `ref` that would be updated by a `_fetchState` watcher, and would be serialized by the server, and deserialized by the client to initialize client state correctly.

This conversion will be easier if the current large media store is split into separate stores: audio, image, allMedia, and singleMedia (for the image/audio detail pages), but that would make for a huge PR that would be difficult to review :(

## Alternatives

Another to go back and refactor the stores to use options API. The options store uses a separate function for creating the store, and because of that does correctly handle hydration on the client side. It calls the `state` function on the server, but hydrates the server state values and makes them reactive on the client. There is even a special `hydrate` option that is only available for the options stores.
With this solution, we won't have to _"fight the tool"_, and will be using the options it provides instead.

## Additional context

The solution for store hydration is implemented in the Provider store PR: #1158.
I have also opened a [discussion in the Pinia repository](https://github.com/vuejs/pinia/discussions/1213) about the composition store state hydration, but it's still unanswered.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1254 by @obulat

## Description

This is the last store that needed to be converted from a Pinia setup store to an options store. 
`active-media` store can also be converted, but because it's not used in server-rendered pages, it's not necessary.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/stores/nav.ts [hunk 1]
```diff
@@ -1,39 +1,26 @@
...
-const NAV = 'nav'
-
 /**
  * Store information about navigation.
  */
-export const useNavStore = defineStore(NAV, () => {
-  /* State */
-
-  const state: NavState = reactive({
+export const useNavStore = defineStore('nav', {
```
Comment (krysal) [inline src/stores/nav.ts:11]:
```suggestion
export const useNavigationStore = defineStore('navigation', {
```
🙏

**Review by krysal — APPROVED** [review]
I will appreciate if we use the full name of this module as the rest. Otherwise, LGTM.

**Review by sarayourfriend — APPROVED** [review]
LGTM!
