### PR TITLE
Fix Search form on smaller viewports

### LINKED ISSUE #436: SearchGridForm  adjusts to screen size changes incorrectly
## Description

The search form input and button have different heights based on the screen width, and they are currently updated incorrectly such that the input height does not match the button height.

Also, the logic of adding a margin to the inline-start of the search form based on filters being open/closed is incorrect.
And the filters opening in modal/sidebar switch is arbitrarily set to 800px screen instead of being one of the tailwind breakpoint values. 
## Reproduction

1. Run the app using `npm run dev`
2. Go to `https://localhost:8443/search/image?q=cat`
3. Open filters and change screen width. 
4. You should see the search input inconsistencies as in the screenshots:

## Expectation

The search input and button heights should be the same, and there should be a space between "Filters" button and the search input.

## Screenshots

Screen Shot 2021-11-19 at 12 17 57 PM
Screen Shot 2021-11-19 at 12 17 40 PM

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #436 by @obulat
Related to #428 by @obulat

## Description

This PR adjusts the styles of the search grid form on screens smaller than `lg`.
This is the view for small/large screen with these changes:

Screen Shot 2021-11-19 at 12 35 41 PM

Screen Shot 2021-11-19 at 12 35 26 PM

Here is the current version:

Screen Shot 2021-11-19 at 12 17 57 PM

Screen Shot 2021-11-19 at 12 17 40 PM

  It also fixes the Checkbox checkmark for RTL by changing the `left` positioning value to `start`.
Screen Shot 2021-11-19 at 12 16 30 PM

## Testing Instructions

Run the app and search for something, change the screen width, open and close filters and see that the search form height is consistent, and there is a space between the "Filters" button and the search form.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM! 🚀

File: src/components/SearchGridForm.vue [hunk 1]
```diff
@@ -10,14 +10,13 @@
       v-if="!isFilterVisible"
       class="button filter-toggle"
       type="button"
-      @click.prevent="onToggleSearchGridFilter()"
-      @keyup.enter.prevent="onToggleSearchGridFilter()"
+      @click.prevent="onToggleSearchGridFilter"
```
Comment (dhruvkb) [inline src/components/SearchGridForm.vue:13]: Unrelated to your changes but why `.prevent`? Since the button has `type="button"`, it has no default action associated with it.

**Review by dhruvkb — APPROVED** [review]
LGTM.

File: src/components/SearchGridForm.vue (hunk 1 above)
Comment (obulat) [reply src/components/SearchGridForm.vue:13]: Good catch, @dhruvkb ! I found why it had `.prevent`: because this button used to be an `a` link: https://github.com/WordPress/openverse-frontend/commit/21407eb40153f2dfb697cb9be5541770d41acffb#diff-42fd9b361230feaa7e4766d70160004df481bc85f3519588c860d09ea0ab9573R40
