### PR TITLE
Fix homepage accessibility

### LINKED ISSUE #652: Animating the placeholder text on homepage is bad for accessibility
## Description

Animating the placeholder text of the search bar on the homepage every 100ms is a big problem for accessibility. We should find alternative approaches for this animation.

## Reproduction

1. Visit homepage using AT.
4. Experience the horror.

## Expectation

The animation should be a purely ornamental aspect of the homepage, and should completely cease to exist for assistive technologies.

## Additional context

This issue was branched from the homepage PR #593 with a possible solution in https://github.com/WordPress/openverse-frontend/pull/593#issuecomment-1017668491.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #652 by @dhruvkb 

## Description

Switches to a static version of the homepage that randomly selects a set of featured images to show. To avoid creating any accessibility problems with these images, they're wrapped in `aria-hidden`.

This removes the animated placeholder text. There is an `aria-label` on the search input that indicates it is for searching.

`VInputField`'s `sr-only` label element was causing a weird "Safari is busy" bug with VoiceOver. Replacing it with an `aria-label` has the same effect as the `sr-only` label element but fixes this bug (I don't know why this bug is happening but we can dig into that a later date).

## Testing Instructions

Checkout this branch and run `pnpm dev`. Visit the site in Safari with VoiceOver and verify that you can successfully navigate the homepage and execute a search.

Note: there are other problems with moving from the homepage to the search results, but I've opened a separate issue to solve those here: https://github.com/WordPress/openverse-frontend/issues/659

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Thanks for addressing this so quickly. Perhaps we can eventually make an improvement where we show the 'featured search' term somewhere else, not related to the input, and get these images cycling again in the short future.

File: src/pages/index.vue [hunk 1]
```diff
@@ -23,16 +23,17 @@
...
         @submit="handleSearch"
       >
-        <VContentSwitcherPopover
-          v-if="isMounted && isMinScreenMd"
-          ref="contentSwitcher"
-          class="mx-3"
-          :active-item="contentType"
-          @select="setContentType"
-        />
+        <ClientOnly>
```
Comment (dhruvkb) [inline src/pages/index.vue:28]: It might be hard to understand why this is client only (because I don't get it). Do you think an explanatory comment `<!-- -->` here might be justified?

File: src/pages/index.vue [hunk 2]
```diff
@@ -57,28 +58,22 @@
...
+        <NuxtLink
+          v-for="(image, index) in featuredSearch.images"
           :key="image.identifier"
-          name="fade"
-          mode="out-in"
-          appear
+          :to="image.url"
+          class="homepage-image block aspect-square h-30 w-30 lg:h-auto lg:w-auto lg:m-[2vh] rounded-full"
+          :style="{ '--transition-index': `${index * 0.05}s` }"
         >
```
Comment (dhruvkb) [inline src/pages/index.vue:69]: Should we preserve the one-by-one fade-in animation? That might still look quite nice on the static page?

File: src/pages/index.vue [hunk 3]
```diff
@@ -154,61 +142,8 @@ const HomePage = {
...
-    }
-
-    const isMounted = ref(false)
-    onMounted(() => {
-      isMounted.value = true
-    })
-    onBeforeUnmount(() => {
-      isMounted.value = false
-    })
+    const featuredSearchIdx = Math.floor((Math.random() * 10) % 3)
```
Comment (dhruvkb) [inline src/pages/index.vue:145]: Nit: Since `Math.random()` is `[0, 1)`, multiplying by 3 gives `[0, 3)`, which can be floored to give `{0, 1, 2}` directly.
```suggestion
    const featuredSearchIdx = Math.floor(Math.random() * 3)
```

File: src/pages/index.vue [hunk 4]
```diff
@@ -225,7 +160,7 @@ const HomePage = {
     const searchTerm = ref('')
     const handleSearch = async () => {
       await store.dispatch(`${SEARCH}/${UPDATE_QUERY}`, {
-        q: searchTerm.value || featuredSearches[featuredSearchIdx.value].term,
+        q: searchTerm.value,
```
Comment (dhruvkb) [inline src/pages/index.vue:163]: We would still need the fallback string when the user hits search without typing anything?

File: src/pages/index.vue [hunk 5]
```diff
@@ -23,16 +23,17 @@
       <VSearchBar
         v-model.trim="searchTerm"
         class="max-w-[40rem] mt-4 lg:mt-8"
-        :placeholder="featuredSearchText"
```
Comment (dhruvkb) [inline src/pages/index.vue:26]: In the absence of animation, I suppose placing the featured search term as the placeholder is justified?

**Review by dhruvkb — CHANGES_REQUESTED** [review]

File: src/pages/index.vue (hunk 1 above)
Comment (sarayourfriend) [reply src/pages/index.vue:28]: I don't know why it is client only, I was actually hoping you did! `ClientOnly` just removes the extra logic that we previously had for the `isMounted` ref that was being maintained.

File: src/pages/index.vue (hunk 5 above)
Comment (sarayourfriend) [reply src/pages/index.vue:26]: Placeholders get read by the screen reader. Without the visual context of the opposite side of the screen, it would be a completely context-less placeholder and the screen reader would read "Olympic games" and the person relying on a screen reader would have no idea why.

File: src/pages/index.vue (hunk 2 above)
Comment (sarayourfriend) [reply src/pages/index.vue:69]: Sure thing.

**Comment by panchovm** [comment]
Can we add a static placeholder that says `Search for content`? An input without label nor placeholder looks odd.

File: src/pages/index.vue (hunk 1 above)
Comment (dhruvkb) [reply src/pages/index.vue:29]: 🤷

**Review by dhruvkb — APPROVED** [review]
