### PR TITLE
Fix mature content report submission

### LINKED ISSUE #1079: Mature content report submission is broken
Attempt to report an image as 'mature' and the form fails to submit. It appears to be the result of a malformed API path.

When this is fixed, we need to include an accompanying test to ensure this can not happen again.

## Screenshot

CleanShot 2022-03-08 at 14 00 46@2x

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #1079 by @zackkrida 
Related to #1086 by @krysal 

## Description

This PR:
- fixes the mature content report submission by passing the id correctly and removing the extra `/` when building URL in the data service
- update Axios to the last version
- (no related to mentioned issues) adds a catch method to silence an annoying console error in Firefox when navigating by related images (in development mode). If you know a better way to handle this, please share it.

## Testing Instructions

Try to report any image, you should see the success message and the request must have been sent.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [-] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/pages/image/_id.vue [hunk 1]
```diff
@@ -160,9 +160,17 @@ const VImageDetailsPage = {
...
+        axios
+          .head(event.target.src)
+          .then((res) => {
+            this.imageType = res.headers['content-type']
+          })
+          .catch(() => {
+            /**
+             * Do nothing. This avoid the console warning "Uncaught (in promise) Error:
+             * Network Error" in Firefox in development mode.
+             */
```
Comment (sarayourfriend) [inline src/pages/image/_id.vue:172]: I don't see this error when I remove this `catch` :thinking:

Is there something specific we should do to handle this network error in actuality rather than ignoring it like we have been? I'm not sure what the effect of not having the image type defined is.

File: src/components/VContentReport/VContentReportForm.vue [hunk 2]
```diff
@@ -162,7 +164,7 @@ export default defineComponent({
       // Submit report
       try {
         await service.sendReport({
-          identifier: props.media.identifier,
+          identifier: props.media.id,
```
Comment (sarayourfriend) [inline src/components/VContentReport/VContentReportForm.vue:167]: :disappointed: Can't wait for TS to make these types of bugs a thing of the past for us :slightly_smiling_face:

**Review by sarayourfriend — APPROVED** [review]
LGTM! The mature report works now, I can see the request being sent in my browser's network debugger.

File: src/pages/image/_id.vue (hunk 1 above)
Comment (krysal) [reply src/pages/image/_id.vue:172]: I'm not sure what to do other than ignore but maybe it's better to hide it in the UI instead of showing "Unknown". Could be related to this Sentry issue too https://sentry.io/share/issue/a7dd1a0bf2304516a38ec5ac065d4049/ ?

File: src/data/report-service.js [hunk 3]
```diff
@@ -6,7 +6,7 @@ const ReportService = {
   sendReport(params) {
     const mediaType = params.mediaType ?? IMAGE
     return VersionedApiService.post(
-      `/${getResourceSlug(mediaType)}${params.identifier}/report/`,
+      `/${getResourceSlug(mediaType)}${params.identifier}/report`,
```
Comment (dhruvkb) [inline src/data/report-service.js:9]: I'm not sure about removing this slash. The API endpoint has a slash, and `APPEND_SLASH` set to true so the post data will be lost in the redirect.

Screenshot 2022-03-16 at 11 28 58 AM

Comment (dhruvkb) [reply src/data/report-service.js:9]: And when I send the same request to the API, I get 405 Method Not Allowed (presumably because Django went ahead with the redirect and it became a GET request).
Screenshot 2022-03-16 at 11 31 15 AM

**Review by dhruvkb — APPROVED** [review]
