### PR TITLE
Tweaks to the Image Details page

### LINKED ISSUE #1111: Wrong font size on image details page and has horizontal scrolling on mobile
In our effort to remove legacy styles, some changes affected parts of the image details page.

## Reproduction

1. Run the project and go to the image details page of any image
2. Observe the font size of the license descriptions, it should be the `sm` size of our tailwind config (`13px`) on mobile and `base` (14px) on desktop.
3. Notice that it presents a horizontal scrolling

## Expectation

The page should match the Figma mockups [[mobile](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=958%3A19663), [desktop](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=1228%3A21557)] and shouldn't have horizontal scrolling.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #1111 by @krysal

## Description

This PR fixes the font size of the license description and breaks words in the attribution HTML tab to avoid causing horizontal scrolling when the page is on small screens.

## Testing Instructions

Follow steps on issues and compare with Figma mockups.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [-] I added or updated tests for the changes I made (if applicable).
- [-] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
This looks good, thank you! It's tricky, the designs use a base font of 14px, but we can't set it globally because it seems to alter the entire page layout. Hopefully this is the last component that needs `text-base` manually specified.

File: src/components/VContentReport/VContentReportForm.vue [hunk 1]
```diff
@@ -60,12 +60,12 @@
 
         <div class="mb-4 min-h-[7rem]">
           <VDmcaNotice
-            v-if="selectedReason === reasons.DMCA"
+            v-if="media.foreign_landing_url && selectedReason === reasons.DMCA"
```
Comment (obulat) [inline src/components/VContentReport/VContentReportForm.vue:63]: Thank you for fixing this! The warnings were bothering me. I guess they are fired before the 'image' object is loaded, when the image detail is pre-fetched.

**Review by obulat — APPROVED** [review]
Looks great!
I have only noticed one small thing: the Report content button is charcoal-70 in the mockups, and is just charcoal currently. It is out of scope for this PR, though, so feel free to merge without changing.
