### PR TITLE
Fix flaky audio a11y tests

### LINKED ISSUE #1567: Playwright tests are broken and blocking PRs
## Description

See these two runs on separate PRs, neither of which modify the actual app:

https://github.com/WordPress/openverse-frontend/runs/7326438723?check_suite_focus=true
https://github.com/WordPress/openverse-frontend/runs/7327276653?check_suite_focus=true

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #1567  by @sarayourfriend 

## Description

Refactors the audio keyboard accessibility tests to account for the loading state. I'm surprised this wasn't an issue earlier.

This appears to have fixed the flakiness of the tests :crossed_fingers: 

## Testing Instructions

`pnpm test:playwright` and confirm none fail. Also confirm CI for the same passes.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VAudioTrack/VPlayPause.vue [hunk 1]
```diff
@@ -41,13 +41,6 @@ import playIcon from '~/assets/icons/play.svg'
 import pauseIcon from '~/assets/icons/pause.svg'
 import replayIcon from '~/assets/icons/replay.svg'
 
-const statusVerbMap = {
-  playing: 'pause',
-  paused: 'play',
-  played: 'replay',
-  loading: 'loading',
-} as const
```
Comment (sarayourfriend) [inline src/components/VAudioTrack/VPlayPause.vue:49]: Had to move this so that it could be accessible from Playwright as we don't have Playwright configured to know how to import from `.vue` SFCs.

File: test/playwright/e2e/all-results-keyboard.spec.ts [hunk 2]
```diff
@@ -92,8 +96,27 @@ test.describe('all results grid keyboard accessibility test', () => {
...
     await page.keyboard.press(keycodes.Spacebar)
     const focusedResult = await locateFocusedResult(page)
-    await expect(focusedResult.locator('[aria-label="Pause"]')).toBeVisible()
+    await expect(await audio.getActive(focusedResult)).toBeVisible()
     await page.keyboard.press(keycodes.Spacebar)
-    await expect(focusedResult.locator('[aria-label="Play"]')).toBeVisible()
+    await expect(await audio.getInactive(focusedResult)).toBeVisible()
+  })
+
+  test('should pause audio after playing another', async ({ page }) => {
```
Comment (sarayourfriend) [inline test/playwright/e2e/all-results-keyboard.spec.ts:104]: Adding this new test because I realized we were kind of missing this one.

**Review by krysal — APPROVED** [review]
Apart from a leftover line, everything looks correct 👍

File: test/playwright/utils/audio.ts [hunk 3]
```diff
@@ -0,0 +1,72 @@
+import { expect, Locator } from '@playwright/test'
```
Comment (sarayourfriend) [inline test/playwright/utils/audio.ts:1]: I kind of hate this module, mostly the implicit assertions that it makes... they feel gross but having to return `Promise<Locator | null>` just means that the expect gets pushed up to the test level instead of a `not.toBeNull()`. Maybe that is better though. My feeling with tests is that the more explicit they are the better, even if they seem repetitive... Do others agree with this? Obviously there's a lot of utility in sharing logic for selecting elements or doing routine actions, but as far as assertions go I think it's nice to have them hoisted up into the test itself :thinking:

**Review by obulat — APPROVED** [review]
Great addition! I hope it fixes the CI failures for other PRs, too.
