### PR TITLE
Fix licence information flyout menu alignment

### LINKED ISSUE #219: [Bug] License information flyout menu alignment
The license information popover/flyout/menu thing doesn't align with the "?" icon that triggers it.

CleanShot 2021-09-15 at 16 15 22@2x

### PR DESCRIPTION
**Pull request by 0kyn**
## Fixes

Fixes #219 by @zackkrida

## Description

This PR fixes licence information flyout alignement, it makes tooltip dynamically aligned with licence help icon.

## Technical details

Computed CSS properties are calculated once `LicenceExplanationTooltip.vue` component is mounted.  
Some CSS properties related to tooltip box appearance are arbitrary set locally.

### Questions

- Is a good practice to get `event` from `computed()` methods ?
```js
if (event) {
    const helpIconBounding = event.target.getBoundingClientRect()
    // I'm unclear about this
    // ...
}
```

- Instead of setting CSS properties into `data()` method, should it be better to let them defined in `<style>...</style>` and get them through `window.getComputedStyle(this.$el)` ? 

### Desktop
desktop_licence_flyout

### Touch

touch_licence_flyout

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Hi @0kyn apologies for the delay in reviewing this, I will look today and get back to you.

**Review by zackkrida — APPROVED** [review]
Hi @0kyn, I like the approach of setting CSS variables. I made a small change to avoid the computed property `event` accessing stuff, which I've actually never seen before, to instead pass the dom node of the `?` icon to the ToolTip as a prop.

**Comment by 0kyn** [comment]
Hi @zackkrida thanks for the trick! It's pretty interesting, I would never thought about this...

File: src/components/Filters/FilterChecklist.vue [hunk 1]
```diff
@@ -48,9 +48,11 @@
           <LicenseIcons v-if="filterType === 'licenses'" :license="item.code" />
           {{ itemLabel(item) }}
         </label>
+
```
Comment (obulat) [inline src/components/Filters/FilterChecklist.vue:51]: Please, remove the spaces on the empty line (you can also run `npm run format` to remove them automatically)

File: src/components/Filters/FilterChecklist.vue [hunk 2]
```diff
@@ -48,9 +48,11 @@
           <LicenseIcons v-if="filterType === 'licenses'" :license="item.code" />
           {{ itemLabel(item) }}
         </label>
+        
         <button class="appearance-none">
```
Comment (obulat) [inline src/components/Filters/FilterChecklist.vue:52]: There is currently a bug with this button: 
When you click, it reloads the page. This happens because a button inside the form is by default of type "submit", so it currently submits the form (and `stop` modifier on the `@click.stop` handler does not change it). 
Adding "type='button'" will fix this.

Comment (obulat) [inline src/components/Filters/FilterChecklist.vue:52]:
```suggestion
        <button class="appearance-none" type="button">
```

File: src/components/Filters/FilterChecklist.vue (hunk 1 above)
Comment (zackkrida) [inline src/components/Filters/FilterChecklist.vue:51]:
```suggestion

```

**Comment by zackkrida** [comment]
@obulat I've gone ahead and applied the requested changes!

**Review by obulat — APPROVED** [review]
Thank you for another great contribution!
