### PR TITLE
Show album title on audio details page

### LINKED ISSUE #1544: Missing album title
## Description

The UI is not showing the audio title because it's using the wrong field name.

https://github.com/WordPress/openverse-frontend/blob/515693f829e5454e2ab61e2e9f472e17225a854e/src/components/VAudioDetails/VAudioDetails.vue#L29-L31

The audio details page should show the audio set information (title & link) when it's available, as in the [Figma mockups](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=978%3A19107).

## Reproduction
1. Run the project with the API locally on the branch of PR WordPress/openverse-api#769 
```sh
API_URL=http://localhost:8000/ pnpm dev
```
2. See there is not album title in the UI but in the API response
```sh
curl -s "http://localhost:8000/v1/audio/2ab7a881-370e-4a00-ab35-1c8cb99e8e60/" | jq .audio_set
```

```json
{
  "title": "Listen",
  "foreign_landing_url": "https://www.jamendo.com/album/3661/listen",
  "creator": "Tryad",
  "creator_url": "https://www.jamendo.com/artist/104/tryad",
  "url": "https://usercontent.jamendo.com?type=album&id=3661&width=200",
  "filesize": null,
  "filetype": null
}
```

Try with other audio files if you want.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #1544 by @krysal

## Description

Also changes the link to the `foreign_landing_url` as `url` goes to the cover image.

## Testing Instructions

See in the linked issue.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VAudioDetails/VAudioDetails.vue [hunk 1]
```diff
@@ -26,8 +26,8 @@
           <div v-if="audio.audio_set">
             <dt>{{ $t('audio-details.table.album') }}</dt>
             <dd>
-              <VLink :href="audio.audio_set.url">{{
-                audio.audio_set.name
+              <VLink :href="audio.audio_set.foreign_landing_url">{{
+                audio.audio_set.title
```
Comment (sarayourfriend) [inline src/components/VAudioDetails/VAudioDetails.vue:30]: Can you also update the `audio_set` type to have `title` and `url` properties (or even all the properties that are available from the catalog)?

https://github.com/WordPress/openverse-frontend/blob/698e608c28955f111b36ce20bd3134902a41d454/src/models/media.ts#L57

Because we haven't added this file to the tsconfig.json TS check isn't failing here when it should because `audio_set` is just a `string`.

File: test/unit/specs/components/VAudioDetails/v-audio-details.spec.js [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+  })
+
+  it('renders the album title', () => {
+    render(VAudioDetails, options)
+    const album = screen.getByText(overrides.audio_set.title)
+    expect(album).toHaveAttribute(
+      'href',
+      overrides.audio_set.foreign_landing_url
+    )
+  })
```
Comment (sarayourfriend) [inline test/unit/specs/components/VAudioDetails/v-audio-details.spec.js:38]: Can you also add a test for the opposite case, where it should not try to render the album information?

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
LGTM! Just a couple small things :rocket:

File: test/unit/specs/components/VAudioDetails/v-audio-details.spec.js (hunk 2 above)
Comment (krysal) [reply test/unit/specs/components/VAudioDetails/v-audio-details.spec.js]: Done! :)

**Review by sarayourfriend — APPROVED** [review]
Excellent! :tada:

**Review by dhruvkb — APPROVED** [review]
This is great! Looking forward to seeing more audio info in the details.
