### PR TITLE
Replace download button with foreign landing button

### LINKED ISSUE #1250: Freesound download buttons link incorrectly
## Description

Freesound download results do not work. We should fix this in the catalog, but also add a special exception in the frontend ASAP to link off the Freesound download buttons to the freesound page for the track itself.

## Reproduction

1. Visit any Freesound result: https://wordpress.org/openverse/audio/9af3243a-e4d4-4254-95d9-a3d53a0158c3
2. Click the download button
3. Observe the result is the failed API credential page: https://freesound.org/apiv2/sounds/20015/download/

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #1250 by @zackkrida 

## Description

As agreed in [this comment](https://github.com/WordPress/openverse-frontend/issues/1250#issuecomment-1100136519) this PR replaces the audio format download button with a link button to the foreign landing URL for the track.

I also deleted the unused dropdown and download button components. They're not exactly implemented in a way that I think we would implement them today (I was still very much learning Vue when I wrote them) and we can write better ones if we decide we need this again (or just restore them from the git history if we don't have time).

## Testing Instructions

Checkout the branch and run `pnpm dev`. Visit an audio track like `/audio/3b95bd5f-55fe-4b6f-be83-26a3e5886674` and check the download button. Visit another and make sure it works :slightly_smiling_face: 

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VAudioTrack/layouts/VFullLayout.vue [hunk 1]
```diff
@@ -58,24 +58,27 @@
...
 
-import VDownloadButton from '~/components/VDownloadButton.vue'
+import VButton from '~/components/VButton.vue'
 import VLink from '~/components/VLink.vue'
 
 export default defineComponent({
   name: 'VFullLayout',
-  components: { VDownloadButton, VLink },
+  components: { VButton, VLink },
   props: ['audio', 'size', 'status', 'currentTime'],
```
Comment (obulat) [inline src/components/VAudioTrack/layouts/VFullLayout.vue:82]: Could we add the proptypes here?

File: src/components/VAudioTrack/layouts/VFullLayout.vue [hunk 2]
```diff
@@ -58,25 +58,45 @@
...
+      type: Object,
+      required: true,
+    },
+    size: {
+      type: String,
+      validation: (v) => ['s', 'm', 'l'].includes(v),
+    },
+    status: {
+      type: String,
+      validation: (v) => ['playing', 'played', 'ejected'].includes(v),
```
Comment (krysal) [inline src/components/VAudioTrack/layouts/VFullLayout.vue:93]: I think this should be "paused" instead of "ejected". 
```suggestion
      validation: (v) => ['playing', 'played', 'paused'].includes(v),
```

**Review by krysal — APPROVED** [review]
LGTM!

**Review by obulat — APPROVED** [review]
LGTM!
I wonder if we should add some indication that the button opens a new tab on the provider site? @panchovm ? The way when clicking on the button for the fist time, someone might get confused.

**Comment by sarayourfriend** [comment]
@obulat yes, agreed!

**Comment by panchovm** [comment]
> I wonder if we should add some indication that the button opens a new tab on the provider site?

Yes. Very agree. I would also suggest having a consistent label for all main actions in the single result view. `Open [content-type]'s website` is a good phrase for image, audio, and all the upcoming new types.

I will create a design issue for enhancing the button component
