### PR TITLE
Make VLink component that wraps around both external and internal links

### LINKED ISSUE #468: External links NOT opening in the Openverse iframe
## Description

On the single image result page, a click on a creator's link causes error in an iframe due to x-frame settings.

## Reproduction

1. Go to any single result page, for example [this one](https://wordpress.org/openverse/photos/20708f1c-0978-47ab-8855-e01f3a392ab3)
2. Click on the creator's name (pricklysarah)
3. See an error:
 - in Firefox the iframe shows a warning "Firefox Can’t Open This Page. To protect your security, www.flickr.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.", with a button to open the page in a new window
 - in Chrome, the iframe is gray and seems to be stuck, but there is a faint text saying "www.flickr.com refused to connect."

## Expectation

The link should open. I think the best option would be to open it in a new tab. Another option is to set the target to the top window, so that the link opens in the same tab

## Screenshots

image

## Additional context

Because the iframe height was previously set to a high number (around 3000px), it is also hard to see the error message in Chrome, as it appears much lower than the fold.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #468 by @obulat

## Description

This PR supercedes #468, based on @krysal 's [comment about wrapping internal links, too](https://github.com/WordPress/openverse-frontend/pull/871#pullrequestreview-883719330).

Now, `VLink` is a wrapper component that should be used for all links. It determines whether the link is internal or external by checking if the `href` attr starts with `/`.

**External links:**
- use `a` element.
- add `target='_blank'` that allows the links to open in another tab, instead of causing errors in an iframe.
- adds `rel='noopener noreferrer' to prevent some referrer vulnerabilities in older browsers (`target='_blank'` is enough for modern browsers)

**Internal links:**
- use `NuxtLink` component.
- wrap the `href` in `app.localePath` to ensure that the correct locale is used, and pass it as the `to` prop to `NuxtLink`.

This PR moves the warning for missing `href` from `VButton` to `VLink`, so `VButton` doesn't have to handle the lack of `href` property.

## Testing Instructions

Run the app and test out internal links and external links. Also check that the links in the navbar (pages) work as expected. External links should always open in a new tab.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VLink.vue [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    const linkComponent = computed(() => (isInternal.value ? 'NuxtLink' : 'a'))
+    const { href, ...otherProperties } = attrs
+
+    // No need to declare `href` as an explicit prop as Vue preserves
+    // the `attrs` object reference between renders and updates the properties
+    // meaning we'll always have the latest values for the properties on the
+    // attrs object
+    if (!href || href === '#') {
+      warn('VLink is missing a valid `href` attribute.')
+    }
```
Comment (sarayourfriend) [inline src/components/VLink.vue:32]: Just a nit, but this will only warn on the first render of the component. That _might_ be okay but it could be more useful to watch `attrs.href` and warn any time it's an invalid value.

File: src/components/VLink.vue [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+import { computed, defineComponent, useContext } from '@nuxtjs/composition-api'
+import { warn } from '@/utils/warn'
+const defaultProps = { target: '_blank', rel: 'noopener noreferrer' }
+export default defineComponent({
+  name: 'VLink',
+  setup(_, { attrs }) {
+    const { app } = useContext()
+    const isInternal = computed(() => attrs.href?.startsWith('/'))
+    const linkComponent = computed(() => (isInternal.value ? 'NuxtLink' : 'a'))
+    const { href, ...otherProperties } = attrs
```
Comment (sarayourfriend) [inline src/components/VLink.vue:24]: Destructuring these from `attrs` will make their values non-reactive in the `computed` for `linkProperties` below. To maintain reactivity they need to stay as properties on `props` or `attrs`.

File: test/unit/specs/components/v-link.spec.js [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+import VLink from '~/components/VLink.vue'
+
+jest.mock('~/utils/warn', () => ({ warn: jest.fn() }))
+
+const nuxtLinkStub = {
+  template: '<a v-on="$listeners"><slot /></a>',
+  props: ['to'],
+}
+const nuxtContextMock = {
+  $nuxt: { context: { app: { localePath: (v) => v } } },
```
Comment (sarayourfriend) [inline test/unit/specs/components/v-link.spec.js:12]: If we change `localePath` to a `jest.fn()` we could test that it get's called with the `to` value for internal links as well.

**Review by sarayourfriend — COMMENTED** [review]
LGTM! Still need to test this locally but I'm still excited for this :tada: The only blocker right now is the `attrs` destructuring... I wish there was an eslint rule to warn against that, I feel like 99% of the time it's probably not the right thing to do. Maybe that's wrong though.

**Comment by sarayourfriend** [comment]
I noticed three more `<a>`'s in the app that could use this:

1. DownloadButton (It's still using the `DropdownButton` component which doesn't use `VButton` underneath)
2. FooterSection: link to 4v licenses
3. FooterSection: link to FontAwesome

File: src/components/VLink.vue [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+export default defineComponent({
+  name: 'VLink',
+  setup(_, { attrs }) {
+    const { app } = useContext()
+    const isInternal = computed(() => attrs.href?.startsWith('/'))
+    const linkComponent = computed(() => (isInternal.value ? 'NuxtLink' : 'a'))
+
+    let linkProperties = {}
+    watch(
+      [attrs],
```
Comment (sarayourfriend) [inline src/components/VLink.vue:34]: Does watching `attrs` like this actually work? :thinking: When I test this locally it doesn't seem to fire the watcher when the attrs change (even though it does re-render). You can see in this example where clicking the button causes the re-render but doesn't fire the watcher to update the value: https://codesandbox.io/s/crazy-rosalind-y12vp4

I think attrs is probably the wrong tool for this anyway... `href` should just be a required string prop, and then we can add the `warn` in the validator function for it.

`watch` _will_ work on props, so we can successfully keep linkProperties updated (in fact, it can just be a `computed` at that point.

Comment (obulat) [reply src/components/VLink.vue:34]: Right! Having href as a prop will ensure that it's not also passed as an attr to NuxtLink! So, there will be no need to destructure the attrs.

File: src/components/VLink.vue [hunk 5]
```diff
@@ -6,50 +6,34 @@
...
 const defaultProps = { target: '_blank', rel: 'noopener noreferrer' }
 
 export default defineComponent({
   name: 'VLink',
-  setup(_, { attrs }) {
+  props: {
+    href: {
+      type: String,
+      required: true,
+      validator: (v) => !['', '#'].includes(v),
```
Comment (sarayourfriend) [inline src/components/VLink.vue:25]: Nice :+1:

**Review by sarayourfriend — COMMENTED** [review]
The MediaTag changes seem unrelated. Was it a faulty merge perhaps? :thinking:

File: src/components/VLink.vue [hunk 6]
```diff
@@ -6,50 +6,34 @@
...
-          : {
-              ...otherProperties,
-              ...defaultProps,
-              href,
-            }
-      },
-      { immediate: true }
+    let linkProperties = computed(() =>
+      isInternal.value
+        ? { to: app?.localePath(props.href) ?? props.href }
```
[the remark this answers is not in the document]
Comment (obulat) [reply src/components/VLink.vue:35]: When testing 😆 That was probably a lazy hack to ensure tests pass without mocking the nuxt context :)

**Comment by obulat** [comment]
> The MediaTag changes seem unrelated. Was it a faulty merge perhaps? 🤔

Do you mean `src/components/VMediaTag/meta/VMediaTag.stories.mdx` changes, @sarayourfriend ?

This PR is kind of very small: adding one component, but it touches so many files!

File: src/components/VLink.vue (hunk 6 above)
[the remark this answers is not in the document]
Comment (sarayourfriend) [reply src/components/VLink.vue:35]: Oh dear! I wish it was easier to set up a globally enabled mock of the nuxt stuff :thinking:

**Comment by krysal** [comment]
Relabelling as "priority: medium" as the linked issue is actually fixed in the main branch and this is more of an improvement.

**Comment by sarayourfriend** [comment]
Oh sorry, I was looking specifically at the merge commit, not the full diff for the PR :facepalm: 

Anyway, it looks like making `props.href` required breaks client-side navigation of the result page :tada: I guess in the interest of not trying to fix too many things at once here we could just make the links wait until `href` is defined to render?

**Comment by obulat** [comment]
> Relabelling as "priority: medium" as the linked issue is actually fixed in the main branch and this is more of an improvement.

I am ok with relabelling, but just want to note that the issue was about all the external `<a>` links, not just the homepage licenses. Try clicking on 'Go to source', or links in the pages menu on search-staging. The links will be opened in the same tab, and with the iframe on w.org, this will break.

File: src/components/VLink.vue [hunk 7]
```diff
@@ -21,19 +23,26 @@ export default defineComponent({
   props: {
     href: {
       type: String,
-      required: true,
-      validator: (v) => !['', '#'].includes(v),
```
Comment (sarayourfriend) [inline src/components/VLink.vue]: nit: I think we can keep the validator, otherwise accidental long-lived invalid `href` values won't ever get caught.

**Review by sarayourfriend — APPROVED** [review]
LGTM! Things no longer crash because of this (there are still _other_ crashes but unrelated to this change :+1:)

**Comment by sarayourfriend** [comment]
@obulat a solution I've used in past projects to easily identify "bad links" is to add some kind of horrific inline-styles to them that make them obviously stand out. Something like `style="background-color: hotpink; border: 2rem solid green;"`

**Review by zackkrida — APPROVED** [review]
lgtm! I've clicked around pretty extensively and text searched for raw `<a>` tags, in the repo, and didn't find anything that shouldn't be there.

Question for @WordPress/openverse-frontend: Does anyone know of an eslint rule we could introduce to warn on raw `<a>` tag usage in our Vue templates?

**Comment by sarayourfriend** [comment]
@zackkrida The [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) rule can probably do it.

**Review by krysal — APPROVED** [review]
@obulat You were right! I forgot about the untouched links on internal pages. It's great we can now be safe about external links with these changes :rocket:

**Comment by zackkrida** [comment]
@obulat I made a small companion PR with an eslint rule to enforce `VLink` usage:

https://github.com/WordPress/openverse-frontend/pull/916
