### PR TITLE
handling null and undefined value for userAgent

### LINKED ISSUE #903: Non-string UserAgent can crash the app
## Description

https://sentry.io/share/issue/e01331b2eb71498080208da9d62de7f1/

If either `context.req.headers['user-agent']` or `navigator.userAgent` return a non-string value, the app crashes, because `useragent.parse` in `'express-useragent' expects a string argument and calls `replace` on it.
This is the error you would see: 
```
TypeError
Cannot read properties of undefined (reading 'replace')
```
Here is the code that causes the error:
https://github.com/WordPress/openverse-frontend/blob/5a3bed0dbab754e88749accc5a59477f7337583b/src/plugins/ua-parse.js#L3-L12

## Reproduction

1. Add `userAgent = null` or `userAgent = undefined` to line 11 in the code above.
2. Run the app and try to open http://localhost:8443
3. See error.

## Expectation

The app should not crash even if the user agent is undefined.
 
## Additional context

I wonder why the user agent can be non-string?

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by kb-0311**
## Fixes

Fixes #903  by @obulat 

## Description

explicitly declared the userAgent type as string 

Converted the `context.req.headers['user-agent']` and `navigator.userAgent` to string type. 

This will make sure the `user.parse(userAgent)`  always gets a string value as an argument.
`
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kb-0311** [comment]
I cannot really add labels to a PR can someone please help me out with the labels ?

**Comment by zackkrida** [comment]
Hm, I'm not sure we want to use a solution like this, for this reason:

```
String(null) === 'null'
String(undefined) === 'undefined'
```

**Comment by kb-0311** [comment]
@zackkrida 
What exactly do you want to parse as userAgent in case it is null or undefined?

**Comment by sarayourfriend** [comment]
I guess the more correct thing to do would be to set `$ua` to `null`  and force downstream users of that context variable to decide how to handle when it's not present?

**Comment by kb-0311** [comment]
@sarayourfriend 
Hey so I tried to do what I thought I understood from your comment please suggest the changes to be made

**Review by obulat — APPROVED** [review]

File: src/plugins/ua-parse.js [hunk 1]
```diff
@@ -8,7 +8,12 @@ export default function (context, inject) {
   } else if (typeof navigator !== 'undefined') {
     userAgent = navigator.userAgent
   }
-  const ua = useragent.parse(userAgent)
+  var ua
```
Comment (sarayourfriend) [inline src/plugins/ua-parse.js:11]: I'm not sure why our linter isn't complaining about this line, we have the `no-var` rule enabled :confused: 

```suggestion
  let ua
```

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
This actually becomes a bigger change once we do this, we'll need to update the places that consume this context to check for `null`:

https://github.com/WordPress/openverse-frontend/blob/6c938c1c6bb7fca75b937749f8e14acddd69eb2c/src/composables/use-browser-detection.js#L3-L15

I think the `useBrowserIsBlink` and `useBrowserIsMobile` functions can just return `false` if the return type from `useBrowserDetection` is `null`.

We'll also need to update the types here to include `null`, `$ua: UADetails | null`:

https://github.com/WordPress/openverse-frontend/blob/6c938c1c6bb7fca75b937749f8e14acddd69eb2c/typings/nuxt__types/index.d.ts#L7

File: src/plugins/ua-parse.js (hunk 1 above)
Comment (kb-0311) [reply src/plugins/ua-parse.js:11]: And I will make the necessary changes to `use-browser-detection.js` and index.d.ts too. Thanks for the heads up.

**Comment by kb-0311** [comment]
@sarayourfriend Hey so, I am not sure why I am getting the null type error in my recent commit. Are there changes to be made in some other file that accepts a string value of `useBrowserIsMobile()` or some other way null handling should have been done ?

**Review by sarayourfriend — APPROVED** [review]
This LGTM! Please do change the `mobile` variable to `browser` if you decide to keep it instead of the optional chaining approach, but otherwise this is great! Thanks so much for the contribution :tada:

File: src/composables/use-browser-detection.js [hunk 2]
```diff
@@ -7,9 +7,18 @@ export const useBrowserDetection = () => {
...
+  if (browser !== null) {
+    return browser.isChrome || browser.isEdge || browser.isOpera
+  } else {
+    return false
+  }
 }
 
 export const useBrowserIsMobile = () => {
-  return useBrowserDetection().isMobile
+  const mobile = useBrowserDetection()
```
[the remark this answers is not in the document]
Comment (kb-0311) [reply src/composables/use-browser-detection.js:18]: thanks for the suggestion however I would say more beginners like myself would find the if-else statements easier to understand rather than ternary operators. if there are some optimization issues I will do it.

Yes for sure the `mobile` variable was just a placeholder for the logic. I will change it to `browser` .

**Comment by obulat** [comment]
Thank you for your contribution, @kb-0311 !
