### PR TITLE
Fix navbar keyboard accessibility

### LINKED ISSUE #116: [Bug] Impossible to focus nav bar items using keyboard navigation
## Description
Using only keyboard navigation, it is not possible to focus the nav bar items. They're not tabbable elements so the browser skips over them and right onto the search box.

## Reproduction

1. Open the frontend
2. Using the `tab` button, attempt to focus the nav bar dropdowns like the About and Resources dropdowns.

## Expectation
The dropdowns and their individual items should be focusable using keyboard navigation.

## Environment

This isn't environment specific. I've confirmed it with and without VoiceOver in Safari and Firefox on macOS.

## Additional context
I'm not sure why this is happening as the nav elements are all just plain anchor elements, but something is causing them to not be focusable.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #116  by @sarayourfriend 

## Description
Adds a Dropdown component based on [Vuetensils' Dropdown](https://raw.githubusercontent.com/AustinGil/Vuetensils/production/src/components/VDropdown/VDropdown.vue) to make the navbar keyboard accessible.

## Technical details
Heavily modifies the Vuetensils' Dropdown to accomodate a couple of things:

0. Make the keyboard navigation behave the same as WordPress.org's navbar (i.e., no arrow key navigation, just tabbing through each item in order)
1. Adds focus management to each child by making an `onFocus` prop available through the default slot. This `onFocus` prop should be used in the `@focus` for each dropdown item. This makes it possible to tab "backwards" from a subsequent navbar item. For example, in the real example of the Openverse dropdown if you <kbd>Shift + Tab</kbd> from the Web Extension navbar item, you should focus into the last item of the Resources dropdown, not the Resources dropdown itself.
2. Makes the dropdown container always rendered into the DOM by using the visually hidden styles, lifted from `@wordpress/components`. This makes the dropdown items always appear in the DOM, making them keyboard focusable while hiding them from sighted users.
3. Use Bulma classes to fit the existing implementation. This is a drop-in replacement for the existing implementation, style wise, but adds keyboard accessibility (there should be no visual differences between this and the existing implementation).

## Tests
If you're on macOS, ensure that you've enabled keyboard navigation in the accessibility options following the instructions here: https://www.a11yproject.com/posts/2017-12-29-macos-browser-keyboard-navigation/

After restarting your browser, you should be able to tab through the navbar items including the dropdown items. Compare this to the live site and you'll see that it was not previously possible.

There are also unit tests to ensure that the focus management works (by teseting the presence of the `visible` class on the dropdown wrapper).

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/Dropdown.vue [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+  <div
+    class="navbar-item has-dropdown is-hoverable"
+    @mouseenter="isHovered = true"
+    @mouseleave="isHovered = false"
+    @focus="isFocused = true"
+    @blur="isFocused = false"
+    @focusout="onFocusout"
+  >
+    <div
+      :aria-expanded="!!isHovered || !!isFocused"
```
Comment (obulat) [inline src/components/Dropdown.vue:13]: Can isHovered ever be not boolean? Do we really need the !! in front of it?

File: src/components/Dropdown.vue [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+const Dropdown = {
+  name: 'Dropdown',
+  props: {
+    /**
+     * The trigger element text.
+     */
+    text: {
+      type: String,
+      default: '',
+    },
```
Comment (obulat) [inline src/components/Dropdown.vue:57]: This could be 'required' since we lways have text in the dropdown trigger.

File: src/components/Dropdown.vue [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+      this.isFocused = true
+    },
+  },
+}
+
+export default Dropdown
+</script>
+
+<style lang="scss">
+.navbar-dropdown {
```
Comment (obulat) [inline src/components/Dropdown.vue:93]: Can we change this in the original scss navbar file insidethe styles folder?

**Review by obulat — APPROVED** [review]
This is fantastic, Sara. I have left some tiny comments and questions inline. So great to improve a11y on such a vital part of the site!

File: src/components/Dropdown.vue (hunk 1 above)
Comment (sarayourfriend) [reply src/components/Dropdown.vue:13]: I think you're right 👍

Comment (sarayourfriend) [reply src/components/Dropdown.vue]: Done in 25b141e

File: src/components/Dropdown.vue (hunk 2 above)
Comment (sarayourfriend) [reply src/components/Dropdown.vue:55]: Fixed in 25b141e

File: src/components/Dropdown.vue (hunk 3 above)
Comment (sarayourfriend) [reply src/components/Dropdown.vue]: Done in d0c6ebe

File: src/components/Dropdown.vue (hunk 2 above)
Comment (sarayourfriend) [reply src/components/Dropdown.vue:55]: Done in 25b141e

**Review by zackkrida — APPROVED** [review]
LGTM! I appreciate the jest `--watch` script as well.
