### PR TITLE
Remove focus on SearchBar after submit

### LINKED ISSUE #1367: Executing search on mobile using the keyboard 🔎 key does not close the keyboard
## Description

When you use mobile keyboard's 🔎 key to submit search from the header, the keyboard doesn't close. 

## Reproduction

1. Open https://search-staging.openverse.engineering/search/image?q=cat on a mobile phone.
2. In the header search bar, change the search term.
3. Press the mobile keyboard 🔎 button. 
4. See error: the keyboard is still open.

## Screenshots

https://user-images.githubusercontent.com/15233243/166218654-2760bf88-f0c5-4a5f-96a3-de0ff3468b76.mp4

## Environment

 - Device: Samsung phone
 - OS: Android
 - Browser: Firefox

## Additional context

The solution is probably to `blur()` the input element on search form submit.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by rafaelytakei**
## Fixes

Fixes #1367 by @obulat 

## Description
Removes the focus on the search bar after submitting a search.
This is done by adding a simple `document.activeElement?.blur()` after the search is done.

## Testing Instructions

Navigate to a search result page, and try searching for something else through the header. After submitting with the `Enter` key or the search button on keyboard (if mobile), the search field should no longer be focused.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VHeader/VHeader.vue [hunk 1]
```diff
@@ -204,6 +204,7 @@ const VHeader = defineComponent({
       })
       router.push(newPath)
       await mediaStore.fetchMedia()
+      document.activeElement?.blur()
```
Comment (sarayourfriend) [inline src/components/VHeader/VHeader.vue:207]: Can we move the blurring before the fetching media? Otherwise when you search there is a delay while the new results are fetched before the keyboard disappears.

**Review by sarayourfriend — DISMISSED** [review]
Thank you so much @rafaelytakei for your contribution and welcome to Openverse :tada: 

This works great! I just have one request to tighten up the UX a little bit and then I will approve :woman_dancing:

**Review by obulat — APPROVED** [review]
Great solution, @rafaelytakei ! It works well, and will work even better after you move the line up, as suggested in the other review.
Thank you for your contribution, and welcome to Openverse! 🎉

File: src/components/VHeader/VHeader.vue (hunk 1 above)
Comment (obulat) [inline src/components/VHeader/VHeader.vue:207]:
```suggestion
      document.activeElement?.blur()
      await mediaStore.fetchMedia()
```

**Review by zackkrida — APPROVED** [review]
I've merged in the small change suggested by @obulat and @sarayourfriend; this looks great, thank you @rafaelytakei!
