### PR TITLE
Fix/e2e tests

### LINKED ISSUE #1637: Playwright CI does not fail when Playwright fails with status 1
## Description

When the Playwright tests fail in CI, the container exits with code 1, but the CI still passes. 
Here's a link to such a run:
https://github.com/WordPress/openverse-frontend/runs/7751696961?check_suite_focus=true

<details>
<summary>CI logs</summary>
```
 Creating openverse-frontend_playwright_1 ... done
Attaching to openverse-frontend_playwright_1
playwright_1  | 
playwright_1  | > openverse-frontend@2.2.1 test:playwright:local /app
playwright_1  | > DISABLE_SENTRY=true playwright test -c test/playwright "--workers=2"
playwright_1  | 
playwright_1  | 
playwright_1  | Running 269 tests using 2 workers
playwright_1  | 
playwright_1  | 2022-08-09T17:32:05.910Z pw:webserver Starting WebServer process ./node_modules/.bin/npm-run-all -p -r talkback prod...
playwright_1  | 2022-08-09T17:32:05.920Z pw:webserver Process started
playwright_1  | 2022-08-09T17:32:05.920Z pw:webserver Waiting for availability...
playwright_1  | [WebServer] /bin/sh: 1: ./node_modules/.bin/npm-run-all: not found
playwright_1  | 2022-08-09T17:32:05.924Z pw:webserver Waiting 100ms
playwright_1  | 
playwright_1  | Error: Process from config.webServer was not able to start. Exit code: 127
playwright_1  | 
playwright_1  | 
playwright_1  | 
playwright_1  | 
playwright_1  |   269 skipped
playwright_1  |  ELIFECYCLE  Command failed with exit code 1.
openverse-frontend_playwright_1 exited with code 1
1
Aborting on container exit...
Removing openverse-frontend_playwright_1 ... 
Removing openverse-frontend_playwright_1 ... done
Removing network openverse-frontend_default
```
</details>

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1637 by @obulat

## Description

This PR fixes the failing Playwright visual regression tests, and makes the CI fail if Playwright tests fail.

The changes introduced in #1559 to stop the Docker container after Playwright tests caused the CI not to fail even if the Playwright container exits with status `1`.

As can be seen in [this run](https://github.com/WordPress/openverse-frontend/runs/7785041855?check_suite_focus=true)'s log, **Playwright tests started to fail** again after the following line from `bin/playwright.sh` was removed:
`docker-compose -f docker-compose.playwright.yml down`

I've also updated the snapshots that were failing.

## Testing Instructions

Look at the CI logs. The most recent ones are passing, but the run before that should fail because one of the snapshots didn't match.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: bin/playwright.sh [hunk 1]
```diff
@@ -9,8 +9,8 @@ export PLAYWRIGHT_ARGS=$@
 export PLAYWRIGHT_VERSION=$(version)
 export TEST_COMMAND=${TEST_COMMAND:-test:playwright:local}
 
-echo Running Playwright v$PLAYWRIGHT_VERSION as $USER_ID with Playwright arguments $PLAYWRIGHT_ARGS
+cp -r test/locales/* src/locales
```
Comment (sarayourfriend) [inline bin/playwright.sh:12]: I wonder if it's worth doing this in the Dockerfile.playwright instead of in here.

File: bin/playwright.sh [hunk 2]
```diff
@@ -9,8 +9,8 @@ export PLAYWRIGHT_ARGS=$@
...
 
-docker-compose -f docker-compose.playwright.yml up --build --force-recreate --abort-on-container-exit --exit-code-from playwright --remove-orphans
+echo Running Playwright v$PLAYWRIGHT_VERSION as $USER_ID with Playwright arguments $PLAYWRIGHT_ARGS
 
-docker-compose -f docker-compose.playwright.yml down
+docker-compose -f docker-compose.playwright.yml up --build --force-recreate --exit-code-from playwright --remove-orphans
```
Comment (sarayourfriend) [inline bin/playwright.sh:16]: So was it the `docker-compose down` that was causing this not to fail because the script continued to the `dc down` command after the failure of the test run? If so, an alternative fix (assuming the `down` is necessary) would be to add `set -x` to the top of the script so that any command failure causes the script to exit with the failure exit code.

Comment (obulat) [reply bin/playwright.sh:16]: Well, if you remove the `dc down` line, the tests start to fail again. But I'm not very clear as to what exactly happens.

Comment (sarayourfriend) [reply bin/playwright.sh:16]: If that is the case then I think it is what I said. The default behavior with shell scripts is not to bail out the entire script if a command fails unless the `e` option is set. 

I had remembered it wrong, btw, it should be `set -e`. `set -x` prints the commands as they're run. `e` bails on the script if any error occurs.

Comment (obulat) [reply bin/playwright.sh:15]: It worked! Thank you :)
How did you see that the Docker container was still running after tests in GitHub actions, by the way?

Comment (sarayourfriend) [reply bin/playwright.sh:15]: >  How did you see that the Docker container was still running after tests in GitHub actions, by the way?

What do you mean?

Comment (krysal) [reply bin/playwright.sh:15]: I was going to suggest using `docker-compose run --rm ...` instead but glad to see it's working now! :)

Comment (sarayourfriend) [reply bin/playwright.sh:15]: I don't remember why but `dc run` did not work for me when I tried it when originally developing the dockerized Playwright tests. There was something strange about it where it would never end the containers, IIRC.

Comment (obulat) [reply bin/playwright.sh:15]: > What do you mean?

The `dc down` line was added to solve the problem where a Playwright container wouldn't stop, right? I have never known that it didn't stop in the CI. How did you understand that that **was**, indeed, happening?

File: bin/playwright.sh (hunk 1 above)
Comment (obulat) [reply bin/playwright.sh]: I removed it because we actually need the matching locale file in other tests, not only the Playwright ones.
When the `valid-locales.json` is not copied in setup-env step in other tests such as Storybook, the app fails to build. Also, simply copying the `valid-locales.json` is not enough because the app requires all of the translation `json` listed in `valid-locales.json` to build.

**Review by dhruvkb — APPROVED** [review]
Looks good to me! Couldn't have foreseen the `set -e` fix.

**Review by sarayourfriend — APPROVED** [review]
LGTM :rocket:

File: bin/playwright.sh (hunk 2 above)
Comment (sarayourfriend) [reply bin/playwright.sh:15]: I think @krysal added it (IIRC) upon noticing that the containers weren't stopping _locally_. I don't think it matters if the containers continue to run in CI, as far as I know.

Comment (krysal) [reply bin/playwright.sh:15]: > I think @krysal added it (IIRC) upon noticing that the containers weren't stopping locally.

That is correct. The machines running the GH actions are a big black box, so that would have been much more difficult to identify, though locally it was a coincidence 🙂

**Comment by krysal** [comment]
I was going to ask why are we marking all the tests to run in parallel mode? I did that for the slowest tests in my PR, those that triggered warnings after the test execution. If we want to do that we can set it up in the Playwright config file (`test/playwright/playwright.config.ts`) instead of repeating the line in every test file.

**Comment by obulat** [comment]
@krysal, I first marked the e2e tests that were triggering the 'slow test' warning, and then just went ahead and added that line in every file.
What is the downside to setting up the parallel execution for all files in the Playwright config file? Adding or removing the line manually based on the test logs seems tedious and we might forget to do it.
Should I open an issue for removing this line from fast tests, or for adding the comment to the Playwright config file?
