### PR TITLE
Fix 'scroll to top' button

### LINKED ISSUE #247: [Bug] "To the top" arrow visually button broken
## Description
The "to the top" arrow button in the corner of the results page is broken visually

## Reproduction
Go to `/search/image?q=dogs` and observe the to the top arrow button in the bottom corner.

## Expectation
The arrow should be centered

## Screenshots
Captura de Tela 2021-09-20 às 13 19 34

## Environment

 - Device: laptop
 - OS: macOS
 - Browser: Confirmed in Chrome and Firefox
 - Version: Evergreen

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #247 by @sarayourfriend

## Description

This PR gives the 'ScrollButton.vue' back to top component a refresh:

- Transitional blue background cover and hover bg color
- New WordPress 'chevron up' SVG 
- Uses constants for spacing instead of arbitrary numbers

CleanShot 2021-09-30 at 16 52 31@2x

## Testing Instructions

- Scroll down the page and view it!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/ScrollButton.vue [hunk 1]
```diff
@@ -2,20 +2,19 @@
   <button
     v-if="showBtn"
     :aria-label="$t('browse-page.aria.scroll')"
-    class="scroll"
+    class="scroll text-white bg-trans-blue hover:bg-trans-blue-action transition-all duration-100 ease-linear fixed right-4 bottom-4 w-14 h-14 hover:shadow-md rounded-full text-center"
```
Comment (obulat) [inline src/components/ScrollButton.vue:5]: Can we use @apply here?

**Review by obulat — APPROVED** [review]
Thank you for fixing this

File: src/components/ScrollButton.vue (hunk 1 above)
Comment (zackkrida) [reply src/components/ScrollButton.vue:5]: I'll make a discussion today, but I think we need to talk about our Tailwind usage as a team before encouraging particular design patterns.

File: src/components/ScrollButton.vue [hunk 2]
```diff
@@ -2,20 +2,19 @@
...
+      aria-hidden="true"
+      focusable="false"
+      class="w-full h-full fill-curr"
     >
-      <path
-        fill="#fff"
-        d="M3.352 48.296l28.56-28.328 28.58 28.347c.397.394.917.59 1.436.59.52 0 1.04-.196 1.436-.59a2.003 2.003 0 000-2.849l-29.98-29.735c-.2-.2-.494-.375-.757-.475a2.052 2.052 0 00-2.166.456L.479 45.447a2.003 2.003 0 000 2.849 2.045 2.045 0 002.873 0z"
-      />
+      <path d="M6.5 12.4L12 8l5.5 4.4-.9 1.2L12 10l-4.5 3.6-1-1.2z" />
     </svg>
```
Comment (sarayourfriend) [inline src/components/ScrollButton.vue:18]: If we're using the WP SVGs... is it possible to use the `@wordpress/icons` package directly instead of inlining the SVGs and repeating them? Or is that a no-go because it's tied to React in some way?

File: tailwind.config.js [hunk 3]
```diff
@@ -16,6 +16,7 @@ module.exports = {
       'dark-turquoise': '#05b5da',
       'dark-slate-blue': '#3c5c99',
       'trans-blue': '#3e58e1',
+      'trans-blue-action': '#5067e4',
```
Comment (sarayourfriend) [inline tailwind.config.js:19]: Hmmm.. isn't "trans" blue `#55CDFC`? 😅 

https://www.schemecolor.com/transgender-pride-flag-colors.php

**Review by sarayourfriend — APPROVED** [review]
LGTM! 🚀

File: src/components/ScrollButton.vue (hunk 2 above)
Comment (zackkrida) [reply src/components/ScrollButton.vue:18]: Yep, it looks like it exports the icons as react components: https://github.com/WordPress/gutenberg/tree/trunk/packages/icons

I thought _maybe_ there'd be the "raw" SVG files in the package, but no such luck.

Comment (sarayourfriend) [reply src/components/ScrollButton.vue:18]: Aww that stinks! Oh well!

File: tailwind.config.js (hunk 3 above)
Comment (zackkrida) [reply tailwind.config.js:19]: heh, our color looks closer to the brand color of this freight company: https://transblue.org

killer domain name!
