### PR TITLE
Stop opening `/search/video` from crashing the app

### LINKED ISSUE #1428: "/search/video" URL crashes app
## Description

Navigating to `/search/video` causes the app to crash.

## Reproduction

- https://search.openverse.engineering/search/video/
- https://search-staging.openverse.engineering/search/video

## Additional context

https://sentry.io/share/issue/0168474ee4fd4a62b3f891089a2f21d9/

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1428 by @AetherUnbound

## Description

This PR makes it possible to open a `/search/video` page without crashing the app (mostly for users that get redirected from CC Search). It doesn't add `Video` to the Content Switcher.
To make sure everything works, I had to make the types more flexible, and make some methods accept `SearchType` (i.e., All Content and all media types including `video` and `media_3d`) instead of `SupportedSearchType`.

This PR is probably a good precursor for #1410, which will add the ability to add more types to the Content Switcher, making it possible to open the `model-3d` and `video` pages through the UI and not only by using the URL with the type in path.

With this PR, you will not be able to open `model-3d` page because we still haven't added a page component (`pages/model-3d`). I think we should add it, no matter what the `AdditionalTypes` flag value is, so that opening a `/search/model-3d` page doesn't crash the app, and the `AdditionalTypes` flag should control whether we have the ability to change the search type via UI (the Content switcher in the header or homepage searchbar).

## Testing Instructions

Try opening `/search/video` or `search/video?q=cat` and make sure it doesn't crash anymore.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VContentSwitcher/VSearchTypePopover.vue [hunk 1]
```diff
@@ -2,7 +2,7 @@
   <VPopover
     ref="contentMenuPopover"
     class="flex items-stretch"
-    :label="$t('search-type.label')"
+    :label="$t('search-type.label').toString()"
```
Comment (krysal) [inline src/components/VContentSwitcher/VSearchTypePopover.vue:5]: why does localized text need to be converted to string in templates? 🤔

File: src/stores/search.ts [hunk 2]
```diff
@@ -259,6 +270,8 @@ export const useSearchStore = defineStore('search', {
         this.setSearchTerm(urlQuery.q.trim())
       }
       this.searchType = queryStringToSearchType(path)
+      console.log('search type set to', this.searchType)
```
Comment (krysal) [inline src/stores/search.ts:273]:
```suggestion
```

**Review by krysal — COMMENTED** [review]
I think we should add `video` to the Content Switcher as the metasearch is available and it was a part of the old CC Search. Currently is showing 3D models, which doesn't crash the app but returns the 404 error page, which seems correct to me since we don't support it even in the metasearch(?), so to me, we should remove 3D models from there until is "semi-supported" at least.

File: src/components/VContentSwitcher/VSearchTypePopover.vue (hunk 1 above)
Comment (obulat) [reply src/components/VContentSwitcher/VSearchTypePopover.vue:5]: Because for TypeScript, i18n does not return string, it returns `TranslationResult`, and it's getting flagged in the templates. It should be fixed in newer versions of i18n library, and hopefully we'll remove all `toString()`s when we update.

**Comment by obulat** [comment]
> I think we should add `video` to the Content Switcher as the metasearch is available and it was a part of the old CC Search. Currently is showing 3D models, which doesn't crash the app but returns the 404 error page, which seems correct to me since we don't support it even in the metasearch(?), so to me, we should remove 3D models from there until is "semi-supported" at least.

We actually do support 3D models in metasearch, and if you add the page component, it will open the page with buttons with links to several providers.
We could define the "support" for additional types under the flag as the addition of the types to the Content switcher. Otherwise, if both page and the Content switcher are under the flag, we would have video treated separately because we need the support for `/search/video` for redirects.

**Comment by krysal** [comment]
@dhruvkb Could you take a look at this today or tomorrow? Thank you!

**Review by zackkrida — APPROVED** [review]
This looks like a good approach to fix the crash, and the extra types in places are a nice touch. It will be very nice to just enable video and 3d model meta search soon as well, but this is a great solution until then.
