### PR TITLE
Fix VIconButton default variant

### LINKED ISSUE #1206: Incorrect styles on reporting form close button
## Description

The content reporting form shows the incorrect button styles, with a pink background that should not be present.

## Reproduction

1. Submit a mature content report.
2. Observe the incorrect button styles

## Screenshots

CleanShot 2022-03-30 at 09 39 53@2x

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #1206  by @zackkrida 

## Description

Fixes the problem in the linked issue by fixing the root cause in the VIconButton component. Also does some TypeScript stuff to make the VButton easier to use with TypeScript and able to type things like VIconButton that "spread props" to VButton.

## Testing Instructions

Check out the VIconButton implementations in the app and ensure they look good:

* PlayPause button
* Content report form close button
* License explanation tooltip in the filter list
* Global audio player close button

I could add visual-regression tests for each of these but in the interest of expediency I only added it for the particular button in question.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VButton.vue [hunk 1]
```diff
@@ -95,7 +101,7 @@ const VButton = defineComponent({
     as: {
       type: String as PropType<ButtonForm>,
       default: 'button',
-      validate: (val: ButtonForm) => buttonForms.includes(val),
+      validate: (val: unknown) => buttonForms.includes(val as ButtonForm),
```
Comment (obulat) [inline src/components/VButton.vue:104]: TIL!

Comment (sarayourfriend) [reply src/components/VButton.vue:104]: I only changed this because I was trying to get the `ExtractPropTypes` to work correctly with props that have default values. I'll set it back, there's no functional or operational difference either way.

File: src/components/VAudioTrack/VPlayPause.vue [hunk 2]
```diff
@@ -36,22 +36,20 @@ export default defineComponent({
      * the current play status of the audio
      */
     status: {
-      type: String,
-      validator: (val) => ['playing', 'paused', 'played'].includes(val),
+      type: String as PropType<'playing' | 'paused' | 'played'>,
```
Comment (obulat) [inline src/components/VAudioTrack/VPlayPause.vue:39]: We could use the type from active media store here: 
https://github.com/WordPress/openverse-frontend/blob/bccbd1333fd0deb51fdd90a391d65e4666caf554/src/stores/active-media.ts#L7

File: src/components/VButton.vue (hunk 1 above)
Comment (sarayourfriend) [reply src/components/VButton.vue:104]: (Though the `unknown` parameter type is _technically_ more correct).

Comment (sarayourfriend) [reply src/components/VButton.vue:104]: It just doesn't matter because we don't call `validate` directly so the type checking in this function is basically a "whatever" kind of thing.

File: src/components/VAudioTrack/VPlayPause.vue (hunk 2 above)
Comment (sarayourfriend) [reply src/components/VAudioTrack/VPlayPause.vue:39]: It's a different status, this one has "played" instead of "ejected". IIRC there _is_ some distinction, perhaps one for when the player is closed ("ejected") and the other for when the audio has simply finished playing to the end (in which case we show the replay button).

Comment (obulat) [reply src/components/VAudioTrack/VPlayPause.vue:39]: Oh, thank you for explaining :)

**Review by obulat — APPROVED** [review]
The buttons' colors are fixed. There are some size inconsistencies with the mockups:

The close button on the License Popover is the correct size (40x40px), but it probably should be right at the top of the popover (without any padding/margin).
The close button on the content report form is too big (48x48 instead of 40x40)

Do you think we should open a new issue for that?

**Comment by sarayourfriend** [comment]
@obulat I can fix those here.

For the button position, I moved it because it looked awkward and wrong for it to not be vertically aligned with header text of the popover. cc @panchovm on that one.

**Comment by panchovm** [comment]
In both the license Popover and the content report form, I see `48px` as size for the `button` element. Is that for a reason? I am using a `24px` size in the mockups to match other similar buttons. 

Regarding the close button position in popovers, I have pending reviewing the popover style. Some cases have more content than others, and the vertical alignment can blend with the popover's title area. Here is an example.

CleanShot 2022-04-14 at 14 19 05@2x

For now, I would keep it top-right aligned with a top and right margin of `8px`. 

Also, notice that the resting style of the close button is `dark-charcoal` instead of `dark-charcoal-70`. I can create a ticket to add the state styles that interactive components have.

**Comment by obulat** [comment]
I think that the close buttons should be at least 40x40px, because on the mobile phones it's very difficult to click on buttons that are smaller than 40px. This is also an accessibility/SEO requirement that is checked by Google Lighthouse.
If you have a margin of 8px, the 24x24px button looks like it's a 40x40px button. We can have a button that is 40x40px right in the corner of the popover, that looks exactly as the designs, don't you think, @panchovm ?

File: src/components/VButton.vue [hunk 3]
```diff
@@ -63,6 +65,10 @@ const buttonTypes = ['button', 'submit', 'reset'] as const
 
 export type ButtonType = typeof buttonTypes[number]
 
+export type ButtonProps = ProperlyExtractPropTypes<
+  NonNullable<typeof VButton['props']>
+>
```
Comment (krysal) [inline src/components/VButton.vue:70]: Shouldn't this be after the declaration of `VButton`?

**Review by krysal — APPROVED** [review]
LGTM!

**Comment by panchovm** [comment]
The [target size criterion](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) requires a `48px` size, but that is for AAA level. For AA it seems not necessary. Nonetheless, you are right about the size being too small. We already have a `close` [component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=851%3A6222) that has a `32px` for the smallest size. We might go with that.

What do you think?
