### PR TITLE
Replace plain `<img>` tag with `VAudioThumbnail` component

### LINKED ISSUE #636: Audio single result page does not show default artwork if no thumbnail is available
## Description

The search results show default artwork for audio results that do not have a thumbnail. The single result page shows a broken image.

## Reproduction

1. Go to single audio result.
2. See error: the broken thumbnail in the audio details section. Note that related audio correctly shows the default artwork.

## Screenshots

Screen Shot 2022-01-19 at 7 49 08 AM

## Expectation

For audio without thumbnails, single result page should show default artwork.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #636 by @obulat 

## Description

This PR
- replaces the plain `` with the `VAudioThumbnail` component capable of automatically falling back to generated artwork
- makes the artwork generation deterministic so that it remains the same in different appearances of the file
- removes the extra space above the media tags when audio does not have any associated description

## Testing Instructions

0. Check out the branch and run the dev server.
1. Visit the page for an audio track without artwork.
2. See the generated art in the information section.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/VAudioThumbnail/VAudioThumbnail.vue [hunk 1]
```diff
@@ -49,14 +49,45 @@ export default {
...
+    const hash = (str) => {
+      let hash = 0
+      if (str.length === 0) return hash
+      for (let i = 0; i < str.length; i++) {
+        let chr = str.charCodeAt(i)
+        hash = (hash << 5) - hash + chr
+        hash |= 0 // Convert to 32bit integer
+      }
+      return hash
+    }
```
Comment (sarayourfriend) [inline src/components/VAudioThumbnail/VAudioThumbnail.vue:89]: Would it make sense to move these into library functions instead of redefining them for every instance of the audio thumbnail?

It also occurred to me (can be a separate issue) but we can avoid calculating or spending any time on the generated artwork when the audio has a thumbnail using an early return.

**Review by sarayourfriend — APPROVED** [review]
LGTM! I think it'd be a nice refactor to move the static functions into their own module to avoid redefining them for every instance of the component.

**Comment by sarayourfriend** [comment]
Oh I noticed another thing when testing this out locally. For some reason the `alt` text of the artwork flashes briefly when a page loads. I would have expected the generated artwork to at least always be present.

Could this be because we're waiting for an error to happen when resolving `audio.thumbnail`? Given we're always generating the artwork anyway, could we actually flip the conditional and only switch to showing the `img` if loading is successful, and display the generated artwork in the meantime? The pop-in with the alt text temporarily is just a little strange.

File: src/components/VAudioThumbnail/VAudioThumbnail.vue (hunk 1 above)
Comment (zackkrida) [reply src/components/VAudioThumbnail/VAudioThumbnail.vue:89]: +1 to Sara's suggestion; I am using a prng in #618 and would be content to use this one instead!

**Review by zackkrida — APPROVED** [review]
Nice!

File: src/components/VAudioThumbnail/VAudioThumbnail.vue (hunk 1 above)
Comment (dhruvkb) [reply src/components/VAudioThumbnail/VAudioThumbnail.vue]: Makes sense, exporting functions into utils in 418dbfc.
